version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: afim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    networks:
      - backend-network

  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["/wait-for-it.sh", "db:5432", "--", "/startup.sh"]
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge